// GrinForge - GRIN Cuckatoo32 GPU miner, open source, no developer fee.
// Modifications Copyright (c) 2026 albertplastauto
// Portions derived from tromp/cuckoo, Copyright (c) 2013-2020 John Tromp,
// distributed under "The FAIR MINING License" (see LICENSE).
// SPDX-License-Identifier: LicenseRef-Fair-Mining
//
// Host-side verification of a Cuckatoo cycle, plus GRIN's difficulty metric.
//
// PROVENANCE
//   `grin_verify` and `grin_setheader` are adapted from tromp/cuckoo
//   `src/cuckatoo/cuckatoo.h` (Copyright (c) 2013-2020 John Tromp,
//   "The FAIR MINING License"). Changes: made `inline` so the header is safe in a
//   multi-TU build, MSVC-free of __builtin_*, and split into a standalone header
//   without the GNU statement-expression error macros.
//
// The verifier is intentionally an independent implementation path from the
// solver: the benchmark cross-checks every solution the GPU reports, so a solver
// bug cannot silently produce "solutions" that the pool would reject.

#pragma once

#include "grin_params.hpp"
#include "blake2.h"

namespace grin {

enum VerifyCode {
    POW_OK = 0,
    POW_HEADER_LENGTH,
    POW_TOO_BIG,
    POW_TOO_SMALL,
    POW_NON_MATCHING,
    POW_BRANCH,
    POW_DEAD_END,
    POW_SHORT_CYCLE,
};

inline const char* verify_str(int code) {
    static const char* names[] = {
        "OK", "wrong header length", "edge too big", "edges not ascending",
        "endpoints don't match up", "branch in cycle", "cycle dead ends",
        "cycle too short",
    };
    if (code < 0 || code > POW_SHORT_CYCLE) return "unknown";
    return names[code];
}

// Verify that `edges` are ascending and form a 42-cycle in the graph generated by
// `keys`. Returns POW_OK on success.
inline int grin_verify(const word_t edges[PROOFSIZE], siphash_keys* keys) {
    word_t uvs[2 * PROOFSIZE], prev[2 * PROOFSIZE], headu[SIZEMASK + 1], headv[SIZEMASK + 1];
    word_t xor0, xor1, u, v, umasked, vmasked;
    xor0 = xor1 = (PROOFSIZE / 2) & 1;

    memset(headu, -1, sizeof(headu));
    memset(headv, -1, sizeof(headv));
    for (u32 n = 0; n < PROOFSIZE; n++) {
        if (edges[n] > NODEMASK) return POW_TOO_BIG;
        if (n && edges[n] <= edges[n - 1]) return POW_TOO_SMALL;
        u = sipnode(keys, edges[n], 0);
        xor0 ^= uvs[2 * n] = u;
        umasked = (u >> 1) & SIZEMASK;
        prev[2 * n] = headu[umasked];
        headu[umasked] = 2 * n;
        v = sipnode(keys, edges[n], 1);
        xor1 ^= uvs[2 * n + 1] = v;
        vmasked = (v >> 1) & SIZEMASK;
        prev[2 * n + 1] = headv[vmasked];
        headv[vmasked] = 2 * n + 1;
    }
    if (xor0 | xor1) return POW_NON_MATCHING;

    for (u32 n = 0; n < PROOFSIZE; n++) {
        if (prev[2 * n] == (word_t)-1) prev[2 * n] = headu[(uvs[2 * n] >> 1) & SIZEMASK];
        if (prev[2 * n + 1] == (word_t)-1) prev[2 * n + 1] = headv[(uvs[2 * n + 1] >> 1) & SIZEMASK];
    }

    u32 n = 0, i = 0, j;
    do {
        for (u32 k = j = i; (k = prev[k]) != i;) {
            if (uvs[k] >> 1 == uvs[i] >> 1) {
                if (j != i) return POW_BRANCH;
                j = k;
            }
        }
        if (j == i || uvs[j] == uvs[i]) return POW_DEAD_END;
        i = j ^ 1;
        n++;
    } while (i != 0);
    return n == PROOFSIZE ? POW_OK : POW_SHORT_CYCLE;
}

// Derive the siphash keys exactly the way the pool does: BLAKE2b-512 over
// pre_pow || be64(nonce), truncated to 32 bytes and read as four little-endian u64.
inline void grin_setheader(const uint8_t* header, u32 headerlen, siphash_keys* keys) {
    unsigned char hdrkey[32];
    blake2b((void*)hdrkey, sizeof(hdrkey), (const void*)header, (size_t)headerlen, nullptr, 0);
    keys->setkeys((const char*)hdrkey);
}

// GRIN's cyclehash: BLAKE2b-256 over the 42 solution nonces serialised as raw
// little-endian u32 (this is what tromp's run_solver prints and what GRIN hashes
// to derive the solution's achieved difficulty). Returns the number of leading
// zero *bits* in that digest.
inline uint64_t grin_cyclehash_leading_zeros(const uint32_t proof[PROOFSIZE]) {
    uint8_t cyclehash[32];
    blake2b(cyclehash, sizeof(cyclehash), proof, sizeof(uint32_t) * PROOFSIZE, nullptr, 0);
    uint64_t zeros = 0;
    for (int i = 0; i < 32; ++i) {
        if (cyclehash[i] == 0) { zeros += 8; continue; }
        uint8_t byte = cyclehash[i];
        while ((byte & 0x80) == 0) { ++zeros; byte <<= 1; }
        break;
    }
    return zeros;
}

// GRIN graph weight for Cuckatoo32: (2 << (32 - 24)) * 32 == 16384.
inline uint64_t grin_graph_weight(u32 edge_bits) {
    return (2ULL << (edge_bits - 24)) * edge_bits;
}

// Achieved difficulty = graph_weight << leading_zero_bits.
inline uint64_t grin_solution_difficulty(const uint32_t proof[PROOFSIZE], u32 edge_bits) {
    return grin_graph_weight(edge_bits) << grin_cyclehash_leading_zeros(proof);
}

} // namespace grin
